version: '3'

services:
    postgres:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: testuser
            POSTGRES_DB: integration_tests
            POSTGRES_PASSWORD: testuser.pass
        ports:
            - '25433:5432'
